const Novels = [
  {
    novel_id: 1,
    name: "Phong thần diễn nghĩa",
    img: "/img/phong-than-dien-nghia.png",
    anou: "Câu chuyện diễn ra vào cuối triều đại nhà Thương, khi Trụ Vương - vị vua tàn bạo, đắm chìm trong tửu sắc và mê đắm Đát Kỷ, một hồ ly tinh do Nữ Oa sai xuống để trừng phạt. Sự tàn ác của Trụ Vương khiến nhiều chư hầu nổi dậy, trong đó nổi bật là Tây Bá Hầu Cơ Xương và con trai ông là Cơ Phát. Với sự giúp đỡ của Khương Tử Nha, một vị tiên được Ngọc Hư Cung phái xuống trần, Cơ Phát dẫn quân lật đổ Trụ Vương, lập ra nhà Chu. Trong quá trình này, rất nhiều thần tiên, yêu quái tham gia vào cuộc chiến, dẫn đến những trận chiến phép thuật kịch tính. Cuối cùng, Trụ Vương bị diệt, Đát Kỷ bị trừng phạt, và bảng phong thần được lập ra, đưa các vị anh hùng đã hy sinh lên làm thần tiên.",
    route: "phong-than-dien-nghia",
    rating: Math.floor(Math.random() * 5 + 1),
  },
  {
    novel_id: 2,
    name: "Con chó của dòng họ baskerville",
    img: "/img/con-cho-cua-dong-ho-baskerville.png",
    anou: `là một trong những tiểu thuyết trinh thám nổi tiếng nhất của Arthur Conan Doyle, xuất bản năm 1902. Đây là một vụ án ly kỳ của thám tử Sherlock Holmes và trợ lý Dr. Watson, pha trộn giữa trinh thám, kinh dị và yếu tố siêu nhiên.`,
    route: "con-cho-cua-dong-ho-baskerville",
    rating: Math.floor(Math.random() * 5 + 1),
  },
  {
    novel_id: 3,
    name: "Cung đàn sau cuối",
    img: "/img/cung-dan-sau-cuoi.png",
    anou: ` là một tập truyện ngắn của Arthur Conan Doyle, xuất bản năm 1917, nằm trong loạt truyện về thám tử lừng danh Sherlock Holmes. Tập truyện này bao gồm nhiều vụ án khác nhau, nhưng đặc biệt nổi bật với truyện ngắn cùng tên, His Last Bow, được xem là vụ án cuối cùng của Sherlock Holmes trước khi ông nghỉ hưu.`,
    route: "cung-dan-sau-cuoi",
    rating: Math.floor(Math.random() * 5 + 1),
  },
  {
    novel_id: 4,
    name: "Số đỏ",
    img: "/img/so-do.png",
    anou: `là một tiểu thuyết trào phúng nổi tiếng của nhà văn Vũ Trọng Phụng, được xuất bản lần đầu vào năm 1936. Tác phẩm phản ánh xã hội Việt Nam thời kỳ thực dân nửa phong kiến, đặc biệt là tầng lớp thượng lưu thành thị với lối sống suy đồi, giả tạo.`,
    route: "so-do",
    rating: Math.floor(Math.random() * 5 + 1),
  },
  {
    novel_id: 5,
    name: "Sống mòn",
    img: "/img/song-mon.png",
    anou: `là một tiểu thuyết hiện thực của Nam Cao, được viết trong giai đoạn trước Cách mạng tháng Tám. Tác phẩm phản ánh cuộc sống bế tắc, ngột ngạt của tầng lớp trí thức nghèo trong xã hội cũ, đồng thời thể hiện triết lý sâu sắc về cuộc sống và con người.`,
    route: "song-mon",
    rating: Math.floor(Math.random() * 5 + 1),
  },
  {
    novel_id: 6,
    name: "Tắt đèn",
    img: "/img/tat-den.png",
    anou: `là một tiểu thuyết hiện thực xuất sắc của Ngô Tất Tố, được viết vào năm 1939. Tác phẩm tố cáo sâu sắc chế độ phong kiến thực dân tàn bạo, đồng thời thể hiện nỗi khổ cực cùng sự vùng lên mạnh mẽ của người nông dân, mà tiêu biểu là nhân vật chị Dậu.`,
    route: "tat-den",
    rating: Math.floor(Math.random() * 5 + 1),
  },
  {
    novel_id: 7,
    name: "Tam quốc diễn nghĩa",
    img: "/img/tam-quoc-dien-nghia.png",
    anou: `là một trong Tứ Đại Danh Tác của văn học Trung Quốc, được viết bởi La Quán Trung vào thế kỷ 14. Đây là một tiểu thuyết lịch sử – quân sự tái hiện giai đoạn loạn lạc cuối thời Đông Hán và thời kỳ Tam Quốc (Ngụy – Thục – Ngô), khi các anh hùng kiệt xuất tranh đấu để giành quyền lực.`,
    route: "tam-quoc-dien-nghia",
    rating: Math.floor(Math.random() * 5 + 1),
  },
  {
    novel_id: 8,
    name: "Chiếc nhẫn tình cờ",
    img: "/img/chiec-nhan-tinh-co.png",
    anou: `là một tiểu thuyết tình cảm lãng mạn hấp dẫn, xoay quanh những tình huống trớ trêu, định mệnh và sự gắn kết kỳ lạ giữa hai con người xa lạ qua một chiếc nhẫn.`,
    route: "chiec-nhan-tinh-co",
    rating: Math.floor(Math.random() * 5 + 1),
  },
];
const Authors = [
  {
    name: "Arthur Conan Doyle",
    route: "arthur-conan-doyle",
    img: `/img/arthur-conan-doyle.png`,
    date: "1859 - 1930",
    anou: "Sir Arthur Conan Doyle là một nhà văn người Scotland nổi tiếng với tiểu thuyết trinh thám  Sherlock Holmes, tác phẩm được cho là một sáng kiến lớn trong lĩnh vực tiểu thuyết trinh thám. Các tác phẩm của ông bao gồm nhiều truyện khoa học giả tưởng, tiểu thuyết lịch sử, kịch lịch sử, tiểu thuyết, thơ và bút ký.",
    indite: [2, 3, 8],
  },
  {
    name: "Hứa Trọng Lâm(許仲琳)",
    route: "hua-trong-lam",
    img: `/img/hua-trong-lam.png`,
    date: "1560-1630",
    anou: `là một nhà văn Trung Quốc thời nhà Minh, được cho là tác giả của "Phong Thần Diễn Nghĩa" (封神演義)—một trong những tiểu thuyết thần thoại kinh điển của văn học Trung Hoa.`,
    indite: [1],
  },
  {
    name: "Vũ Trọng Phụng",
    route: "vu-trong-phung",
    img: `/img/vu-trong-phung.png`,
    date: "1912-1939",
    anou: "là một nhà văn, nhà báo xuất sắc của Việt Nam thời kỳ đầu thế kỷ 20. Ông nổi tiếng với những tác phẩm phản ánh sâu sắc xã hội Việt Nam thời Pháp thuộc, đặc biệt là những mặt trái, sự tha hóa của con người trong thời buổi kim tiền.",
    indite: [4],
  },
  {
    name: "Nam Cao",
    route: "nam-cao",
    img: `/img/nam-cao.png`,
    date: "1917-1951",
    anou: "là một nhà văn hiện thực lớn (trước Cách Mạng), một nhà báo kháng chiến (sau Cách Mạng), một trong những văn sĩ tiêu biểu nhất thế kỷ 20 của Việt Nam. Ông có nhiều đóng góp quan trọng đối với việc hoàn thiện phong cách truyện ngắn và tiểu thuyết Việt Nam ở nửa đầu thế kỷ 20.",
    indite: [5],
  },
  {
    name: "Ngô Tất Tố",
    route: "ngo-tat-to",
    img: `/img/ngo-tat-to.png`,
    date: "1894-1954",
    anou: "là một nhà văn, nhà báo, nhà Nho học và nhà nghiên cứu có ảnh hưởng ở Việt Nam giai đoạn trước 1954. Ngô Tất Tố được coi là nhà văn hàng đầu của trào lưu hiện thực phê phán ở Việt Nam trước 1945 với các tác phẩm tiêu biểu như Tắt đèn,Việc làng, Tập án cái đình, Lều Chõng.",
    indite: [6],
  },
  {
    name: "La Hán Trung(罗贯中)",
    route: `la-quan-trung`,
    img: `/img/la-quan-trung.png`,
    date: "1330?-1400?",
    anou: `là một trong những nhà văn nổi tiếng nhất trong lịch sử Trung Quốc, được biết đến nhiều nhất với kiệt tác "Tam Quốc Diễn Nghĩa". Ông là người đặt nền móng cho tiểu thuyết chương hồi lịch sử Trung Hoa, có ảnh hưởng sâu rộng đến văn học và văn hóa Á Đông.`,
    indite: [7],
  },
];
const Chapters = [
  {
    novel_id: 1,
    chapter_number: 1,
    title: "Trụ Vương tế miễu bà Nữ Oa",
    content: "/txt/1/chuong1.txt",
  },
  {
    novel_id: 1,
    chapter_number: 2,
    title: "Phản nước Thương, Tô Hộ đề thơ",
    content: "/txt/1/chuong2.txt",
  },
  {
    novel_id: 1,
    chapter_number: 3,
    title: "Xem thơ Tây Bá Hầu, Tô Hộ dâng Ðắc Kỷ",
    content: "/txt/1/chuong3.txt",
  },
  {
    novel_id: 1,
    chapter_number: 4,
    title: "Giết giai nhân, Hồ Ly mượn lệnh",
    content: "/txt/1/chuong4.txt",
  },
  {
    novel_id: 1,
    chapter_number: 5,
    title: "Vân Trung Tử dâng kiếm trừ yêu",
    content: "/txt/1/chuong5.txt",
  },
  {
    novel_id: 2,
    chapter_number: 1,
    title: "Ông Sherlock Homes",
    content: "/txt/2/chuong1.txt",
  },
  {
    novel_id: 2,
    chapter_number: 2,
    title: "Nỗi bất hạnh của dòng họ Baskerville",
    content: "/txt/2/chuong2.txt",
  },
  {
    novel_id: 2,
    chapter_number: 3,
    title: "Điểm mấu chốt",
    content: "/txt/2/chuong3.txt",
  },
  {
    novel_id: 2,
    chapter_number: 4,
    title: "Ngài Henry Baskerville",
    content: "/txt/2/chuong4.txt",
  },
];
export { Novels, Authors, Chapters };
